### ISSUE TITLE
Linking libbrpc.so 时出错

### ISSUE THREAD

**Issue by liaosimin** [brpc/brpc#128] opened 2017-11-24 07:51 UTC
Linking libbrpc.so
/usr/bin/ld: /usr/local/lib/libgflags.a(gflags.cc.o): relocation R_X86_64_32S against `.rodata' can not be used when making a shared object; recompile with -fPIC
/usr/local/lib/libgflags.a: error adding symbols: Bad value
collect2: error: ld returned 1 exit status
Makefile:206: recipe for target 'libbrpc.so' failed
make: *** [libbrpc.so] Error 1

**Comment by jamesge** [comment] 2017-11-24 08:41
Duplicate of #90

**Closed** 2017-11-24 09:04 UTC
