### ISSUE TITLE
compile error 

### ISSUE THREAD

**Issue by 742362144** [brpc/brpc#75] opened 2017-10-17 07:28 UTC
我的环境：
      Ubuntu 16.0.4
      gcc version 5.4.0 20160609 (Ubuntu 5.4.0-6ubuntu1~16.04.5) 
      Make 4.1
      libgflags-dev  2.1.2-3 
      libprotobuf-de  2.6.1-1.3
      libprotoc-dev 2.6.1-1.3
编译时错误如下：
Packing libbrpc.a
Linking protoc-gen-mcpack
src/mcpack2pb/generator.o: In function `mcpack2pb::is_map_entry(google::protobuf::Descriptor const*)':
generator.cpp:(.text+0x381): undefined reference to `google::protobuf::FieldDescriptor::TypeOnceInit(google::protobuf::FieldDescriptor const*)'
src/mcpack2pb/generator.o: In function `mcpack2pb::field_to_string(google::protobuf::FieldDescriptor const*)':
generator.cpp:(.text+0x5b2): undefined reference to `google::protobuf::FieldDescriptor::TypeOnceInit(google::protobuf::FieldDescriptor const*)'
generator.cpp:(.text+0x644): undefined reference to `google::protobuf::FieldDescriptor::message_type() const'
generator.cpp:(.text+0x674): undefined reference to `google::protobuf::FieldDescriptor::enum_type() const'
src/mcpack2pb/generator.o: In function `mcpack2pb::to_mcpack_typestr(google::protobuf::FieldDescriptor const*)':
generator.cpp:(.text+0x7a2): undefined reference to `google::protobuf::FieldDescriptor::TypeOnceInit(google::protobuf::FieldDescriptor const*)'
src/mcpack2pb/generator.o: In function `mcpack2pb::McpackToProtobuf::Generate(google::protobuf::FileDescriptor const*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, google::protobuf::compiler::GeneratorContext*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >*) const':
generator.cpp:(.text+0x1183): undefined reference to `google::protobuf::FieldDescriptor::TypeOnceInit(google::protobuf::FieldDescriptor const*)'
generator.cpp:(.text+0x11d4): undefined reference to `google::protobuf::FieldDescriptor::message_type() const'
generator.cpp:(.text+0x1599): undefined reference to `google::protobuf::FieldDescriptor::TypeOnceInit(google::protobuf::FieldDescriptor const*)'
generator.cpp:(.text+0x1638): undefined reference to `google::protobuf::FieldDescriptor::enum_type() const'
generator.cpp:(.text+0x186d): undefined reference to `google::protobuf::FieldDescriptor::message_type() const'
generator.cpp:(.text+0x1b24): undefined reference to `google::protobuf::FieldDescriptor::TypeOnceInit(google::protobuf::FieldDescriptor const*)'
generator.cpp:(.text+0x1b92): undefined reference to `google::protobuf::FieldDescriptor::TypeOnceInit(google::protobuf::FieldDescriptor const*)'
generator.cpp:(.text+0x21d7): undefined reference to `google::protobuf::FieldDescriptor::TypeOnceInit(google::protobuf::FieldDescriptor const*)'
generator.cpp:(.text+0x222c): undefined reference to `google::protobuf::FieldDescriptor::message_type() const'
generator.cpp:(.text+0x2251): undefined reference to `google::protobuf::FieldDescriptor::message_type() const'
generator.cpp:(.text+0x226c): undefined reference to `google::protobuf::FieldDescriptor::message_type() const'
generator.cpp:(.text+0x22cc): undefined reference to `google::protobuf::FieldDescriptor::message_type() const'
generator.cpp:(.text+0x2380): undefined reference to `google::protobuf::FieldDescriptor::enum_type() const'
generator.cpp:(.text+0x2634): undefined reference to `google::protobuf::FieldDescriptor::TypeOnceInit(google::protobuf::FieldDescriptor const*)'
generator.cpp:(.text+0x2695): undefined reference to `google::protobuf::FieldDescriptor::message_type() const'
generator.cpp:(.text+0x278a): undefined reference to `google::protobuf::FieldDescriptor::TypeOnceInit(google::protobuf::FieldDescriptor const*)'
generator.cpp:(.text+0x2824): undefined reference to `google::protobuf::FieldDescriptor::TypeOnceInit(google::protobuf::FieldDescriptor const*)'
generator.cpp:(.text+0x2892): undefined reference to `google::protobuf::FieldDescriptor::TypeOnceInit(google::protobuf::FieldDescriptor const*)'
generator.cpp:(.text+0x30f9): undefined reference to `google::protobuf::FieldDescriptor::message_type() const'
generator.cpp:(.text+0x32b0): undefined reference to `google::protobuf::FieldDescriptor::TypeOnceInit(google::protobuf::FieldDescriptor const*)'
generator.cpp:(.text+0x35f6): undefined reference to `google::protobuf::FieldDescriptor::TypeOnceInit(google::protobuf::FieldDescriptor const*)'
generator.cpp:(.text+0x3699): undefined reference to `google::protobuf::FieldDescriptor::TypeOnceInit(google::protobuf::FieldDescriptor const*)'
generator.cpp:(.text+0x37ac): undefined reference to `google::protobuf::FieldDescriptor::TypeOnceInit(google::protobuf::FieldDescriptor const*)'
generator.cpp:(.text+0x381b): undefined reference to `google::protobuf::FieldDescriptor::TypeOnceInit(google::protobuf::FieldDescriptor const*)'
generator.cpp:(.text+0x3e0a): undefined reference to `google::protobuf::FieldDescriptor::message_type() const'
generator.cpp:(.text+0x3eef): undefined reference to `google::protobuf::FieldDescriptor::TypeOnceInit(google::protobuf::FieldDescriptor const*)'
generator.cpp:(.text+0x3fe2): undefined reference to `google::protobuf::FieldDescriptor::TypeOnceInit(google::protobuf::FieldDescriptor const*)'
generator.cpp:(.text+0x4051): undefined reference to `google::protobuf::FieldDescriptor::TypeOnceInit(google::protobuf::FieldDescriptor const*)'
generator.cpp:(.text+0x4cda): undefined reference to `google::protobuf::FieldDescriptor::message_type() const'
generator.cpp:(.text+0x54ca): undefined reference to `google::protobuf::FieldDescriptor::TypeOnceInit(google::protobuf::FieldDescriptor const*)'
generator.cpp:(.text+0x563d): undefined reference to `google::protobuf::FieldDescriptor::TypeOnceInit(google::protobuf::FieldDescriptor const*)'
generator.cpp:(.text+0x5786): undefined reference to `google::protobuf::FieldDescriptor::message_type() const'
generator.cpp:(.text+0x5893): undefined reference to `google::protobuf::FieldDescriptor::TypeOnceInit(google::protobuf::FieldDescriptor const*)'
generator.cpp:(.text+0x608a): undefined reference to `google::protobuf::FieldDescriptor::enum_type() const'
generator.cpp:(.text+0x6177): undefined reference to `google::protobuf::FieldDescriptor::enum_type() const'
generator.cpp:(.text+0x6264): undefined reference to `google::protobuf::FieldDescriptor::enum_type() const'
generator.cpp:(.text+0x6371): undefined reference to `google::protobuf::FieldDescriptor::TypeOnceInit(google::protobuf::FieldDescriptor const*)'
generator.cpp:(.text+0x64e8): undefined reference to `google::protobuf::FieldDescriptor::TypeOnceInit(google::protobuf::FieldDescriptor const*)'
generator.cpp:(.text+0x661b): undefined reference to `google::protobuf::FieldDescriptor::TypeOnceInit(google::protobuf::FieldDescriptor const*)'
generator.cpp:(.text+0x6b37): undefined reference to `google::protobuf::FieldDescriptor::message_type() const'
generator.cpp:(.text+0x6c51): undefined reference to `google::protobuf::FieldDescriptor::TypeOnceInit(google::protobuf::FieldDescriptor const*)'
generator.cpp:(.text+0x6d5f): undefined reference to `google::protobuf::FieldDescriptor::message_type() const'
generator.cpp:(.text+0x6e6c): undefined reference to `google::protobuf::FieldDescriptor::TypeOnceInit(google::protobuf::FieldDescriptor const*)'
generator.cpp:(.text+0x6fa0): undefined reference to `google::protobuf::FieldDescriptor::TypeOnceInit(google::protobuf::FieldDescriptor const*)'
generator.cpp:(.text+0x70da): undefined reference to `google::protobuf::FieldDescriptor::TypeOnceInit(google::protobuf::FieldDescriptor const*)'
generator.cpp:(.text+0x712c): undefined reference to `google::protobuf::FieldDescriptor::enum_type() const'
generator.cpp:(.text+0x76ea): undefined reference to `google::protobuf::FieldDescriptor::TypeOnceInit(google::protobuf::FieldDescriptor const*)'
generator.cpp:(.text+0x7781): undefined reference to `google::protobuf::FieldDescriptor::enum_type() const'
generator.cpp:(.text+0x784c): undefined reference to `google::protobuf::FieldDescriptor::enum_type() const'
generator.cpp:(.text+0x7914): undefined reference to `google::protobuf::FieldDescriptor::enum_type() const'
generator.cpp:(.text+0x79e4): undefined reference to `google::protobuf::FieldDescriptor::enum_type() const'
generator.cpp:(.text+0x7ab4): undefined reference to `google::protobuf::FieldDescriptor::enum_type() const'
generator.cpp:(.text+0x7b6c): undefined reference to `google::protobuf::FieldDescriptor::TypeOnceInit(google::protobuf::FieldDescriptor const*)'
generator.cpp:(.text+0x7c54): undefined reference to `google::protobuf::FieldDescriptor::TypeOnceInit(google::protobuf::FieldDescriptor const*)'
generator.cpp:(.text+0x7d3c): undefined reference to `google::protobuf::FieldDescriptor::TypeOnceInit(google::protobuf::FieldDescriptor const*)'
generator.cpp:(.text+0x7e24): undefined reference to `google::protobuf::FieldDescriptor::TypeOnceInit(google::protobuf::FieldDescriptor const*)'
generator.cpp:(.text+0x7f2a): undefined reference to `google::protobuf::FieldDescriptor::TypeOnceInit(google::protobuf::FieldDescriptor const*)'
src/mcpack2pb/generator.o:generator.cpp:(.text+0x7f8c): more undefined references to `google::protobuf::FieldDescriptor::TypeOnceInit(google::protobuf::FieldDescriptor const*)' follow
src/mcpack2pb/generator.o: In function `mcpack2pb::McpackToProtobuf::Generate(google::protobuf::FileDescriptor const*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, google::protobuf::compiler::GeneratorContext*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >*) const':
generator.cpp:(.text+0x83fe): undefined reference to `google::protobuf::FieldDescriptor::enum_type() const'
generator.cpp:(.text+0x84d7): undefined reference to `google::protobuf::FieldDescriptor::enum_type() const'
generator.cpp:(.text+0x8622): undefined reference to `google::protobuf::FieldDescriptor::enum_type() const'
generator.cpp:(.text+0x86f8): undefined reference to `google::protobuf::FieldDescriptor::enum_type() const'
generator.cpp:(.text+0x8a0c): undefined reference to `google::protobuf::FieldDescriptor::TypeOnceInit(google::protobuf::FieldDescriptor const*)'
generator.cpp:(.text+0x8bd0): undefined reference to `google::protobuf::FieldDescriptor::enum_type() const'
generator.cpp:(.text+0x8cd0): undefined reference to `google::protobuf::FieldDescriptor::TypeOnceInit(google::protobuf::FieldDescriptor const*)'
generator.cpp:(.text+0x8dfa): undefined reference to `google::protobuf::FieldDescriptor::enum_type() const'
generator.cpp:(.text+0x8efc): undefined reference to `google::protobuf::FieldDescriptor::TypeOnceInit(google::protobuf::FieldDescriptor const*)'
generator.cpp:(.text+0x8fea): undefined reference to `google::protobuf::FieldDescriptor::TypeOnceInit(google::protobuf::FieldDescriptor const*)'
generator.cpp:(.text+0x90f3): undefined reference to `google::protobuf::FieldDescriptor::enum_type() const'
generator.cpp:(.text+0x91cb): undefined reference to `google::protobuf::FieldDescriptor::enum_type() const'
generator.cpp:(.text+0x92ec): undefined reference to `google::protobuf::FieldDescriptor::TypeOnceInit(google::protobuf::FieldDescriptor const*)'
generator.cpp:(.text+0x93ff): undefined reference to `google::protobuf::FieldDescriptor::enum_type() const'
generator.cpp:(.text+0x961d): undefined reference to `google::protobuf::FieldDescriptor::enum_type() const'
generator.cpp:(.text+0x97d5): undefined reference to `google::protobuf::FieldDescriptor::TypeOnceInit(google::protobuf::FieldDescriptor const*)'
generator.cpp:(.text+0x98f4): undefined reference to `google::protobuf::FieldDescriptor::TypeOnceInit(google::protobuf::FieldDescriptor const*)'
generator.cpp:(.text+0x9cd0): undefined reference to `google::protobuf::FieldDescriptor::TypeOnceInit(google::protobuf::FieldDescriptor const*)'
generator.cpp:(.text+0x9dbe): undefined reference to `google::protobuf::FieldDescriptor::TypeOnceInit(google::protobuf::FieldDescriptor const*)'
generator.cpp:(.text+0x9ecc): undefined reference to `google::protobuf::FieldDescriptor::enum_type() const'
generator.cpp:(.text+0x9f9a): undefined reference to `google::protobuf::FieldDescriptor::enum_type() const'
generator.cpp:(.text+0xa098): undefined reference to `google::protobuf::FieldDescriptor::TypeOnceInit(google::protobuf::FieldDescriptor const*)'
generator.cpp:(.text+0xa115): undefined reference to `google::protobuf::FieldDescriptor::enum_type() const'
generator.cpp:(.text+0xa585): undefined reference to `google::protobuf::FieldDescriptor::enum_type() const'
generator.cpp:(.text+0xa707): undefined reference to `google::protobuf::FieldDescriptor::enum_type() const'
generator.cpp:(.text+0xa7d5): undefined reference to `google::protobuf::FieldDescriptor::enum_type() const'
generator.cpp:(.text+0xa8b8): undefined reference to `google::protobuf::FieldDescriptor::enum_type() const'
src/mcpack2pb/generator.o:(.data.rel.ro._ZTVN9mcpack2pb16McpackToProtobufE[_ZTVN9mcpack2pb16McpackToProtobufE]+0x28): undefined reference to `google::protobuf::compiler::CodeGenerator::GenerateAll(std::vector<google::protobuf::FileDescriptor const*, std::allocator<google::protobuf::FileDescriptor const*> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, google::protobuf::compiler::GeneratorContext*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >*) const'
/tmp/cclCmzkI.o: In function `protobuf_idl_5foptions_2eproto::protobuf_AssignDescriptors()':
idl_options.pb.cc:(.text+0x7d): undefined reference to `google::protobuf::internal::AssignDescriptors(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, google::protobuf::internal::MigrationSchema const*, google::protobuf::Message const* const*, unsigned int const*, google::protobuf::MessageFactory*, google::protobuf::Metadata*, google::protobuf::EnumDescriptor const**, google::protobuf::ServiceDescriptor const**)'
/tmp/cclCmzkI.o: In function `protobuf_idl_5foptions_2eproto::AddDescriptorsImpl()':
idl_options.pb.cc:(.text+0x13a): undefined reference to `protobuf_google_2fprotobuf_2fdescriptor_2eproto::AddDescriptors()'
collect2: error: ld returned 1 exit status
Makefile:197: recipe for target 'protoc-gen-mcpack' failed
make: *** [protoc-gen-mcpack] Error 1

已经搞了一天了。哪位大佬说说这是怎么回事

**Comment by 742362144** [comment] 2017-10-17 08:14
您好，是一样的。我完全按照您安装教程里来的，安装前也更新了源。
libprotobuf  2.6.1-1.3    amd64        protocol buffers C++ library
libprotoc-dev 2.6.1-1.3    amd64        protocol buffers compiler library

**Comment by jamesge** [comment] 2017-10-17 08:15
protobuf-compiler是个独立的包，可以查下版本

**Comment by 742362144** [comment] 2017-10-17 08:15
我一开始以为是我以前单独编译过protobuf的问题，但是我又开了一台机器，他还是这样。我换成clang++编译也是这样。希望听到您的建议，麻烦了

**Comment by 742362144** [comment] 2017-10-17 08:16
我不小心删多了  sry 在这里
protobuf-compi 2.6.1-1.3    amd64        compiler for protocol buffer defi
版本是一致的

**Comment by jamesge** [comment] 2017-10-17 09:36
你看看对应的lib是否都存在吧，我自己的ubuntu 16.04上一切正常，版本和你说的都一样

**Comment by jamesge** [comment] 2017-10-23 05:39
Close the issue due to inability to reproduce. Reopen the issue if you have further issues.

**Closed by jamesge** 2017-10-23 05:39 UTC
