### ISSUE TITLE
关于生成protoc-gen-mcpack失败的问题

### ISSUE THREAD

**Issue by nfjiffy** [brpc/brpc#108] opened 2017-11-15 07:30 UTC
当执行Makefile到protoc-gen-mcpack的时候，就会出现连接错误。
Linking protoc-gen-mcpack
/usr/bin/ld: /usr/lib/x86_64-linux-gnu/libgflags.a(gflags.cc.o): relocation R_X86_64_32 again                                 st `.rodata' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: /usr/lib/x86_64-linux-gnu/libgflags.a(gflags_reporting.cc.o): relocation R_X86_6                                 4_32 against `.rodata.str1.8' can not be used when making a shared object; recompile with -fP                                 IC
/usr/bin/ld: /usr/lib/x86_64-linux-gnu/libgflags.a(gflags_completions.cc.o): relocation R_X86                                 _64_32 against `.rodata.str1.8' can not be used when making a shared object; recompile with -                                 fPIC
/usr/bin/ld: final link failed: Nonrepresentable section on output
collect2: error: ld returned 1 exit status
Makefile:197: recipe for target 'protoc-gen-mcpack' failed
make: *** [protoc-gen-mcpack] Error 1

**Comment by jamesge** [comment] 2017-11-16 04:02
Duplicate of #90

**Closed** 2017-12-04 06:18 UTC
